Sign up done inshallah
aabdoo23/SchedsForums pull request #2
Opened 2024-10-18 11:57 UTC by aabdoo23

#### PR Classification
New feature: Introduced MediatR for handling student creation and set up the database schema.

#### PR Summary
This PR introduces MediatR for handling student creation, sets up the database schema, and updates project configurations.
- Added `StudentsController` in `StudentController.cs` using MediatR for student creation.
- Created initial migration files to set up the database schema.
- Updated `Program.cs` to register new services for persistence, infrastructure, and MediatR.
- Added repository and service interfaces and implementations for `Admin`, `Major`, `Moderator`, and `Student` entities.
- Configured `ForumsDbContext` and added `DbContextRegistrationService` for PostgreSQL database integration.

2024-10-18 13:19 UTC, MostafaHgz requested changes

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/StudentController.cs
> +            _mediator = mediator;
add null check 
`_mediator = mediator ?? throw new ArgumentNullAgreement(nameof(mediator));`

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Api/Program.cs
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommandHandler.cs
> +        private readonly IValidator<CreateStudentDTO> _validator = new CreateStudentValidator();
never use new in .net. we mostly use dependency injection for constructing any new object.

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommandHandler.cs
> +            var validationResult = await _validator.ValidateAsync(request.Student);
from 24-28 will be always repeated in all commands/queries. and we need to keep the code dry
look up `AddValidatorFromAssembly()` in fluent validation docs

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Application/RegisterServices.cs
> +
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Common/BaseUser.cs
> +
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Interfaces/IGenericRepository.cs
> +
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/ServiceConfiguration/ConfigureServices.cs
> +
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/ServiceConfiguration/ConfigureServices.cs
> +        public static IServiceCollection Configure(this IServiceCollection services)
what does this do?

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/ServiceConfiguration/ConfigureValidators.cs
> +        public static IServiceCollection Configure(this IServiceCollection services)
you now have 2 extensions methods to IServiceCollection that are named the same. name the method itself a meaningful name
also this file does nothing

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Validators/BaseUserValidator.cs
> +        public BaseUserValidator()
this validation is repeated in user validation as well. see how to use common validators in fluent validations

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Contexts/ForumsDbContext.cs
> +            modelBuilder.Entity<BaseUser>()
when you get to have 10 entities in the future this method will become 100 lines and will be a nightmare to read. 
check how to modularize model configuration and have a configuration file for each entity

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Contexts/ForumsDbContext.cs
> +
class properties always come first before any methods or constructors
also 2 extra lines here

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Repositories/AdminRepository.cs
> +            _context = context;
add null check for the context here

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Common/BaseUser.cs
> +        protected BaseUser()
remove all these empty constructors as they do nothing

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Repositories/Common/GenericRepository.cs
> +            var entity = await _dbSet.FindAsync(id) ?? throw new NullReferenceException($"Can't find an entity with this Id: {id}.");
this is not null reference exception. this is when something that cannot be null 
also it's not the responsibility of the repository to throw errors. 
this method requires 2 query calls and it only needs one. see how you can delete with one query

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Repositories/Common/GenericRepository.cs
> +            return await _dbSet.FindAsync(id) ?? throw new NullReferenceException($"Can't find an entity with this Id: {id}.");
it's not the responsibility of the repository to throw the error. it should return a nullable value. use `SingleOrDefaultAsync`

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Repositories/MajorRepository.cs
> +            _context = context;
remove all repositories that you didn't use in this story as they are not part of the story scope and you didn't use them
always add null checks for the when injecting. also you're injecting the ForumsDbContext inside the Major repository which is incorrect.

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/DbContextRegistrationService.cs
> +        public static IServiceCollection AddPersistenceServices(this IServiceCollection services)
this adds the DB context not a service

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/PasswordService.cs
> +    public class PasswordService : IPasswordService
what if I want to encrypt or hash any other thing than the password. this should be called `HashingService`

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServicesRegistration.cs
> +            services.AddScoped<IStudentRepository, StudentRepository>();
only student repository is needed remove the rest

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Interface/IBaseService.cs
> +﻿namespace SchedsForums.Interface
this does nothing

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IAdminRepository.cs
> +﻿using SchedsForums.Domain.Entities.Users;
remove all unwanted interfaces

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Interface/IGenericRepository.cs
> +
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +    public class ForumsDbContext : DbContext
rename this to the name of the application

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Contexts/ForumsDbContext.cs
> +        public ForumsDbContext(DbContextOptions<ForumsDbContext> options) : base(options)
you have this file twice

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/PasswordService.cs
> +
remove extra line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +    public class ForumsDbContext : DbContext
you have this file twice

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Major.cs
> +﻿using SchedsForums.Domain.Entities.Common;
only the user entity is related to the story's scope. remove all other entities

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Exceptions/EntityNotFoundException.cs
> +﻿namespace SchedsForums.Domain.Exceptions
remove this exception and use .NET Exceptions

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Domain/Interfaces/IGenericRepository.cs
> +
also all interfaces should be in persistance. if you can't do it due to project dependencies we can check it when we next meet

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/StudentController.cs
> +            //return CreatedAtAction(nameof(GetStudentById), new { id = result.Id }, result);
remove commented line

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/StudentController.cs
> +            var createStudentCommand = new CreateStudentCommand { Student = studentDto };
you should make the body of the request is the command itself without constructing a new one

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommand.cs
> +        public CreateStudentDTO Student { get; set; }
student dto should be the command. it doesn't make sense to have a field inside a class that has a class that has the data. just make the command have the data you want directly

2024-10-18 13:19 UTC, MostafaHgz commented on SchedsForums.Application/BaseDTOs/StudentDTO.cs
> +    public class StudentDTO
is this a request or response. you need to specify

2024-10-18 16:08 UTC, aabdoo23 commented on SchedsForums.Interface/IBaseService.cs
> +﻿namespace SchedsForums.Interface
yet

2024-10-18 16:11 UTC, aabdoo23 commented on SchedsForums.Infrastructure/Contexts/ForumsDbContext.cs
> +        public ForumsDbContext(DbContextOptions<ForumsDbContext> options) : base(options)
i screwed with git, its not wallahy

2024-10-22 06:11 UTC, aabdoo23 commented on SchedsForums.Infrastructure/Repositories/Common/GenericRepository.cs
> +            return await _dbSet.FindAsync(id) ?? throw new NullReferenceException($"Can't find an entity with this Id: {id}.");
why singleOrDefault, im using findasync base on this:
![image](https://github.com/user-attachments/assets/f8ff78e4-9ccc-41a5-a48f-64417267c6ff)

2024-10-22 06:15 UTC, aabdoo23 commented on SchedsForums.Infrastructure/Repositories/MajorRepository.cs
> +            _context = context;
I did remove the repo as it's not a part of the story ok.
but Im referencing the DbContext in the repo, why wrong though

2024-10-22 06:16 UTC, aabdoo23 commented on SchedsForums.Domain/Interfaces/IGenericRepository.cs
> +
ok

2024-10-22 10:30 UTC, merged