Sign In story PR
aabdoo23/SchedsForums pull request #3
Opened 2024-10-22 10:23 UTC by aabdoo23

#### PR Classification
New feature: Introduces repository pattern, authentication services, and database context setup for the SchedsForums application.

#### PR Summary
This PR adds new controllers, services, repositories, and database context configurations to support user authentication and student management.
- **LoginController.cs** and **StudentController.cs**: Added new endpoints for login and student creation using MediatR.
- **Program.cs**: Registered services for database context, repositories, MediatR, and JWT authentication.
- **SchedsForumsDbContext.cs**: Defined DbContext with DbSet properties for users, admins, students, and moderators.
- **CreateStudentCommand.cs** and **LoginCommand.cs**: Added command classes and handlers for student creation and login operations.
- **appsettings.json**: Added JWT configuration settings.

2024-10-25 05:41 UTC, MostafaHgz requested changes

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/LoginController.cs
> +            if (command == null)
if command is null it should never get in here

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/LoginController.cs
> +            try
will you use try catch in every action? 
use exception filter

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/LoginController.cs
> +        public async Task<IActionResult> Login([FromBody] LoginCommand command)
LoginAsync

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/LoginController.cs
> +    public class LoginController : ControllerBase
This should be auth controller and it should have both login and signup

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/BaseDTOs/StudentRequestBaseDTO.cs
> +    public class StudentRequestBaseDTO
This should be UserSignUpRequestDTO

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommand.cs
> +    public class CreateStudentCommand : StudentRequestBaseDTO, IRequest<StudentRequestBaseDTO>
it should be only one dto which is UserSignupRequestDTO

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/BaseDTOs/StudentRequestBaseDTO.cs
> +        public string Name { get; set; }
What is the difference between Name and UserName?

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommandHandler.cs
> +    public class CreateStudentCommandHandler(IStudentRepository studentRepository, IHashingService passwordService, IValidator<CreateStudentCommand> validator) : IRequestHandler<CreateStudentCommand,
add a line between every injected service

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommandHandler.cs
> +            var validationResult = await _validator.ValidateAsync(request,cancellationToken);
didn't we discuss the idea that this is not the correct way to do it?

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommandHandler.cs
> +            return new StudentRequestBaseDTO
how is the response called Request?

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Create/CreateStudentDTO.cs
> +    public class CreateStudentDTO : StudentRequestBaseDTO
what is the reason behind this?

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Login/DTOs/LoginRequestDTO.cs
> +    public class LoginRequestDTO
how is the login dto has no fields?

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Login/LoginCommandHandler.cs
> +            _userRepository = userRepository;
add null check

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Commands/Students/Login/LoginCommandHandler.cs
> +                throw new UnauthorizedAccessException("Invalid credentials");
this should be thrown inside the verifyPassword

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Interfaces/Common/IBaseService.cs
> +    public interface IBaseService
this should be deleted

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Interfaces/Repositories/IStudentRepository.cs
> +namespace SchedsForums.Application.Interfaces.Repositories
if it's empty then it does nothing, remove it

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Interfaces/Services/IAuthService.cs
> +        bool VerifyPassword(BaseUser user, string password);
this should only be used in the login command so just make it there, no need to put it in a separate service

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/Interfaces/Services/IAuthService.cs
> +        string GenerateToken(BaseUser user);
token handling should be in its own JWT service

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/RegisterServices.cs
> +    public static class RegisterServices
rename to Application (or API) DIExtensions

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/RegisterServices.cs
> +        public static IServiceCollection RegisterMediatRServices(this IServiceCollection services)
rename to AddMediatRService

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/RegisterServices.cs
> +            services.AddValidatorsFromAssemblyContaining<CreateStudentValidator>();
this way you'll need to add the validator each time you add a new one and when you have 100 endpoints this method will be a mess. check another way to add all validators

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Application/RegisterServices.cs
> +
remove empty space

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Common/BaseEntity.cs
> +        {
Id field here should be initialized by efcore itself. no need for this. 
created at and updated at should not be initialized in the constructor.

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Users/Admin.cs
> +namespace SchedsForums.Domain.Entities.Users
if it has nothing then it does nothing remove it

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Users/Moderator.cs
> +{
remove

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/AuthService.cs
> +            _config = configuration;
add null check

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/AuthService.cs
> +        public string GenerateToken(BaseUser user)
token handling should be in its own service

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/AuthService.cs
> +            var key = Environment.GetEnvironmentVariable("JWT_KEY") ?? throw new NullReferenceException("Can't find JWT Key in Env Variables.");
this way you'll get the JWT_KEY from the environment with each login request. you only need to get it once. do it in the DI itself
also if you want to go the extra mile, check how to do it with IOptions

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/AuthService.cs
> +                new Claim(ClaimTypes.Name, user.UserName),
Username is a single word

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServicesRegistration.cs
> +    public static class ServicesRegistration
don't use registration. rename this and the name should show that it contains services extension methods

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServicesRegistration.cs
> +        public static IServiceCollection RegisterDbContext(this IServiceCollection services)
use Add instead of Register

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServicesRegistration.cs
> +        public static IServiceCollection RegisterInfrastructureServices(this IServiceCollection services)
add a line between each method (do this across the whole solution

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/IBaseEntity.cs
> +        string Id { get; }
you should separate the IBaseEntity and IAuditableEntity

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/IBaseService.cs
> +﻿namespace SchedsForums.Interface
if it's empty remove it

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/IGenericRepository.cs
> +
remove extra line

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/IGenericRepository.cs
> +    public interface IGenericRepository<T> where T : IBaseEntity
why do we have this file twice?

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IAdminRepository.cs
> +    public interface IAdminRepository: IGenericRepository<Admin>
if it's empty remove it

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IMajorRepository.cs
> +    public interface IMajorRepository : IGenericRepository<Major>
if it's empty remove it

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IModeratorRepository.cs
> +    public interface IModeratorRepository:IGenericRepository<Moderator>
if it's empty remove it

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IModeratorRepository.cs
> +    public interface IModeratorRepository:IGenericRepository<Moderator>
also all of these are not in the scope of the task

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +
remove extra lines

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +        public DbSet<Admin> Admins { get; set; }
only user and student are in the scope of this story

2024-10-25 05:41 UTC, MostafaHgz commented on SchedsForums.Persistence/Services/DbContextRegistrationService.cs
> +                //, b => b.MigrationsAssembly("SchedsForums.Persistence")
what is this?

2024-10-25 13:37 UTC, aabdoo23 commented on SchedsForums.Application/BaseDTOs/StudentRequestBaseDTO.cs
> +        public string Name { get; set; }
Full name and username, username can be used for sign in and it's a unique handle, will add the sign in using username part

2024-10-25 13:38 UTC, aabdoo23 commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommand.cs
> +    public class CreateStudentCommand : StudentRequestBaseDTO, IRequest<StudentRequestBaseDTO>
Agreed

2024-10-25 13:39 UTC, aabdoo23 commented on SchedsForums.Application/Commands/Students/Create/CreateStudentCommandHandler.cs
> +    public class CreateStudentCommandHandler(IStudentRepository studentRepository, IHashingService passwordService, IValidator<CreateStudentCommand> validator) : IRequestHandler<CreateStudentCommand,
okay

2024-10-25 13:49 UTC, aabdoo23 commented on SchedsForums.Application/Commands/Students/Login/DTOs/LoginRequestDTO.cs
> +    public class LoginRequestDTO
I created it and the command but used the command only sorry

2024-10-25 14:13 UTC, aabdoo23 commented on SchedsForums.Application/Interfaces/Services/IAuthService.cs
> +        bool VerifyPassword(BaseUser user, string password);
i dont agree very much, i think its a service related to authentication, so in case there are other auth services they should be together in the same file?

2024-10-25 14:21 UTC, aabdoo23 commented on SchedsForums.Infrastructure/Services/AuthService.cs
> +            var key = Environment.GetEnvironmentVariable("JWT_KEY") ?? throw new NullReferenceException("Can't find JWT Key in Env Variables.");
ok

2024-10-29 08:34 UTC, MostafaHgz requested changes

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/AuthController.cs
> +        [HttpPost("SignUp")]
add line

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Api/Filters/CustomExceptionFilter.cs
> +            }
return inside the if and remove else

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Api/Filters/CustomExceptionFilter.cs
> +            }
refactor this

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Api/SchedsForums.Api.csproj
> +    <ProjectReference Include="..\SchedsForums.Infrastructure\SchedsForums.Infrastructure.csproj" />
api should not depend on infrastructure

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Api/appsettings.json
> +  "JWT": {
this move this to appSettings.Development.json

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/ApplicationDIExtensions.cs
> +        public static IServiceCollection AddValidationServices(this IServiceCollection services)
try 
`services.AddMediatR(configuration => configuration.RegisterServicesFromAssembly(Assembly.GetExecutingAssembly()));` and remove addValidations

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/Commands/BaseUser/Login/LoginCommandHandler.cs
> +    public class LoginCommandHandler(IBaseUserRepository userRepository, IAuthService authService, IJWTService jwtService) : IRequestHandler<LoginRequestDTO, LoginResponseDTO>
divide into multiple lines

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/Commands/BaseUser/Login/LoginCommandHandler.cs
> +            _authService.VerifyPassword(user, request.Password);
rename to password service

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/Commands/BaseUser/SignUp/DTOs/UserSignUpRequestDTO.cs
> +    public class UserSignUpRequestDTO : IRequest<UserSignUpResponseDTO>
rename to command

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/Commands/BaseUser/Login/DTOs/LoginRequestDTO.cs
> +    public class LoginRequestDTO : IRequest<LoginResponseDTO>
rename to command

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/Commands/BaseUser/SignUp/UserSignUpCommandHandler.cs
> +    public class UserSignUpCommandHandler(
rename to student

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Application/Commands/BaseUser/SignUp/UserSignUpCommandHandler.cs
> +        private readonly IBaseRepository<Student> _studentRepository = studentRepository;
add null check

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Common/BaseEntity.cs
> +
remove extra line

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Domain/Entities/Common/BaseEntity.cs
> +        public string Id { get; protected set; } = Guid.NewGuid().ToString();
check this

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Contexts/SchedsForumsDbContext.cs
> +            var entries = ChangeTracker.Entries<BaseEntity>();
filter on IAuditable

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Options/JWTOptions.cs
> +        public int ExpirationMinutes { get; set; } = 15;
use this in a constant

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServiceCollectionExtensions.cs
> +                configuration.GetSection("Jwt").Bind(options);
add null checks on other options

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServiceCollectionExtensions.cs
> +                    ValidIssuer = configuration["Jwt:Issuer"],
use jwtOptions

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Services/AuthService.cs
> +    public class AuthService : IAuthService
password

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Interface/IBaseService.cs
> +﻿namespace SchedsForums.Interface
remove it tany

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IAdminRepository.cs
> +    public interface IAdminRepository: IGenericRepository<Admin>
again

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IMajorRepository.cs
> +    public interface IMajorRepository : IGenericRepository<Major>
again

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Interface/Repositories/IModeratorRepository.cs
> +    public interface IModeratorRepository:IGenericRepository<Moderator>
again

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +        protected override void OnModelCreating(ModelBuilder modelBuilder)
add extra line before

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +            modelBuilder.Entity<BaseUser>()
get config from assembly

2024-10-29 08:34 UTC, MostafaHgz commented on SchedsForums.Persistence/SchedsForums.Persistence.csproj
> +	<PropertyGroup>
remove

2024-10-29 09:27 UTC, aabdoo23 commented on SchedsForums.Persistence/Contexts/ForumsDbContext.cs
> +            modelBuilder.Entity<BaseUser>()
this deleted

2024-10-29 10:45 UTC, aabdoo23 commented on SchedsForums.Api/Filters/CustomExceptionFilter.cs
> +            }
7lw kda?

2024-10-29 10:45 UTC, aabdoo23 commented on SchedsForums.Api/SchedsForums.Api.csproj
> +    <ProjectReference Include="..\SchedsForums.Infrastructure\SchedsForums.Infrastructure.csproj" />
tl3 ynf3

2024-10-29 10:50 UTC, aabdoo23 commented on SchedsForums.Domain/Entities/Common/BaseEntity.cs
> +        public string Id { get; protected set; } = Guid.NewGuid().ToString();
Guid works

2024-10-29 11:24 UTC, MostafaHgz requested changes

2024-10-29 11:24 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/AuthController.cs
> +            _mediator = mediator;
add null check

2024-10-29 11:24 UTC, MostafaHgz commented on SchedsForums.Api/Filters/CustomExceptionFilter.cs
> +        public void OnException(ExceptionContext context)
todo enhance this

2024-10-29 11:24 UTC, MostafaHgz commented on SchedsForums.Infrastructure/ServiceCollectionExtensions.cs
> +            this IServiceCollection services,
afsfsd

2024-10-30 07:30 UTC, MostafaHgz approved these changes

2024-10-30 07:30 UTC, merged