GetPendingModeratorRequestsPaginatedDone
aabdoo23/SchedsForums pull request #9
Opened 2024-11-01 09:33 UTC by aabdoo23

#### PR Classification
Code refactor and feature enhancement.
Too many changes because it is based on the previous branch not origin
#### PR Summary
Refactored repository classes and added new methods, updated service configurations, and added migrations.
- `BaseUserRepository`: Constructor now throws `ArgumentNullException` if `SchedsForumsDbContext` is null.
- `BaseRepository`: Refactored to use parameterized constructor; added `GetTotalCount` and `GetFromTo` methods.
- `ServiceCollectionExtensions`: Updated repository registrations and refactored JWT configuration methods.
- `SchedsForums.Infrastructure.csproj`: Added new `Migrations` folder.

2024-11-06 13:24 UTC, MostafaHgz requested changes

2024-11-06 13:24 UTC, MostafaHgz commented on SchedsForums.Api/Controllers/AdminController.cs
> +        public async Task<IActionResult> GetModeratorSignUpRequestsAsync([FromBody] GetPendingModeratorsQuery query)
Thishould be in a new controller

2024-11-06 13:24 UTC, MostafaHgz commented on SchedsForums.Api/appsettings.Development.json
> -  "JWT": {
Pull from master to update this branch

2024-11-06 13:24 UTC, MostafaHgz commented on SchedsForums.Application/Interfaces/Common/IBaseRepository.cs
> +        Task<IEnumerable<T>> GetFromTo(int pageNumber, int pageSize);
Renamed to get paginated

2024-11-06 13:24 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Admins/GetPendingModerators/GetPendingModeratorsQueryHandler.cs
> +            return new GetPendingModeratorsQueryResponseDTO
Create a single paginted bas response

2024-11-06 13:24 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Admins/GetPendingModerators/GetPendingModeratorsQueryHandler.cs
> +            return new GetPendingModeratorsQueryResponseDTO
Paginated response should return from the query not here as it's common in all queries

2024-11-06 14:49 UTC, aabdoo23 commented on SchedsForums.Api/appsettings.Development.json
> -  "JWT": {
updated

2024-11-07 11:50 UTC, MostafaHgz requested changes

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Application/Interfaces/Common/DTOs/BaseResponseDTO.cs
> +    public class BaseResponseDTO
rename to BaseIdResponseDTO

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Common/DTOs/BaseGetPaginatedDTO.cs
> +    public abstract class BaseGetPaginatedDTO<T>
rename to PaginatedResponseDTO

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Common/DTOs/BaseGetPaginatedDTO.cs
> +        public int ReturnedCount { get; set; }
no need for this

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Common/DTOs/BaseGetPaginatedDTO.cs
> +        public IEnumerable<T> Data { get; set; }
this should be IList<>

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Common/DTOs/BaseGetPaginatedEntityDTO.cs
> +namespace SchedsForums.Application.Queries.Common.DTOs
what does this do

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Common/DTOs/BaseGetPaginatedEntityDTO.cs
> +namespace SchedsForums.Application.Queries.Common.DTOs
this should be in the repository

2024-11-07 11:50 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Repositories/PendingModeratorRepository.cs
> +        public override async Task<IEnumerable<PendingModerator>> GetAllAsync()
remove this

2024-11-08 08:53 UTC, MostafaHgz commented on SchedsForums.Application/Queries/Common/DTOs/PaginatedEntityDTO.cs
> +namespace SchedsForums.Application.Queries.Common.DTOs
I believe we agreed this should be moved to the infrastructure

2024-11-08 08:55 UTC, MostafaHgz requested changes

2024-11-08 08:55 UTC, MostafaHgz commented on SchedsForums.Infrastructure/Repositories/Common/BaseRepository.cs
> +            var returnedCount = data.Count;
this is not used anymore

2024-11-08 11:30 UTC, MostafaHgz approved these changes

2024-11-08 11:32 UTC, merged